name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Change to your main branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10 # Choose your desired Python version

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Build Flask app
      run: |
        python app.py # Replace with the script that builds your Flask app

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./static # Change to the directory where your built static files are stored